version: '3.8'
services:
  nextjs:
    container_name: taxgpt_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
